# Generated by Django 4.2.5 on 2025-02-11 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('tshirt_homme', 'T-shirt Homme'), ('chemise_homme', 'Chemise Homme'), ('polo_homme', 'Polo Homme'), ('pull_homme', 'Pull Homme'), ('veste_homme', 'Veste Homme'), ('manteau_homme', 'Manteau Homme'), ('pantalon_homme', 'Pantalon Homme'), ('short_homme', 'Short Homme'), ('costume_homme', 'Costume Homme'), ('sweat_homme', 'Sweatshirt Homme'), ('hoodie_homme', 'Hoodie Homme'), ('debardeur_homme', 'Débardeur Homme'), ('pyjama_homme', 'Pyjama Homme'), ('sousvetement_homme', 'Sous-vêtements Homme'), ('robe_femme', 'Robe Femme'), ('jupe_femme', 'Jupe Femme'), ('top_femme', 'Top Femme'), ('chemise_femme', 'Chemise Femme'), ('veste_femme', 'Veste Femme'), ('manteau_femme', 'Manteau Femme'), ('pantalon_femme', 'Pantalon Femme'), ('short_femme', 'Short Femme'), ('combinaison_femme', 'Combinaison Femme'), ('pull_femme', 'Pull Femme'), ('cardigan_femme', 'Cardigan Femme'), ('sweat_femme', 'Sweatshirt Femme'), ('hoodie_femme', 'Hoodie Femme'), ('sousvetement_femme', 'Sous-vêtements Femme'), ('pyjama_femme', 'Pyjama Femme'), ('tshirt_enfant', 'T-shirt Enfant'), ('sweat_enfant', 'Sweatshirt Enfant'), ('pantalon_enfant', 'Pantalon Enfant'), ('short_enfant', 'Short Enfant'), ('robe_enfant', 'Robe Enfant'), ('jupe_enfant', 'Jupe Enfant'), ('veste_enfant', 'Veste Enfant'), ('manteau_enfant', 'Manteau Enfant'), ('pyjama_enfant', 'Pyjama Enfant'), ('body_enfant', 'Body Enfant'), ('pull_enfant', 'Pull Enfant'), ('sousvetement_enfant', 'Sous-vêtements Enfant'), ('tshirt', 'T-shirt'), ('jeans', 'Jeans'), ('sweat', 'Sweatshirt'), ('pantalon_sport', 'Pantalon de sport'), ('baskets', 'Baskets'), ('doudoune', 'Doudoune'), ('pyjama', 'Pyjama'), ('casquette', 'Casquette'), ('bonnet', 'Bonnet'), ('echarpe', 'Écharpe'), ('gants', 'Gants')], default='jeans', max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('enfant', 'Enfant')], default='homme', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_en_stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='produits/')),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('noir', 'Noir'), ('blanc', 'Blanc'), ('jaune', 'Jaune')], default='noir', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('session_id', models.CharField(max_length=255)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_postee', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='store.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
