# Generated by Django 4.2.16 on 2025-05-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nouveau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='populaire',
            field=models.BooleanField(default=False),
        ),
    ]
