# Generated by Django 4.2.16 on 2024-09-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(choices=[('rouge', 'Rouge'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('noir', 'Noir'), ('blanc', 'Blanc'), ('jaune', 'Jaune')], default='noir', max_length=20),
        ),
    ]
