# Generated by Django 4.2.16 on 2026-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('tshirt_homme', 'T-shirt Homme'), ('chemise_homme', 'Chemise Homme'), ('polo_homme', 'Polo Homme'), ('pull_homme', 'Pull Homme'), ('veste_homme', 'Veste Homme'), ('manteau_homme', 'Manteau Homme'), ('pantalon_homme', 'Pantalon Homme'), ('short_homme', 'Short Homme'), ('costume_homme', 'Costume Homme'), ('sweat_homme', 'Sweatshirt Homme'), ('hoodie_homme', 'Hoodie Homme'), ('debardeur_homme', 'Débardeur Homme'), ('pyjama_homme', 'Pyjama Homme'), ('sousvetement_homme', 'Sous-vêtements Homme'), ('robe_femme', 'Robe Femme'), ('jupe_femme', 'Jupe Femme'), ('top_femme', 'Top Femme'), ('chemise_femme', 'Chemise Femme'), ('veste_femme', 'Veste Femme'), ('manteau_femme', 'Manteau Femme'), ('pantalon_femme', 'Pantalon Femme'), ('short_femme', 'Short Femme'), ('combinaison_femme', 'Combinaison Femme'), ('pull_femme', 'Pull Femme'), ('cardigan_femme', 'Cardigan Femme'), ('sweat_femme', 'Sweatshirt Femme'), ('hoodie_femme', 'Hoodie Femme'), ('sousvetement_femme', 'Sous-vêtements Femme'), ('pyjama_femme', 'Pyjama Femme'), ('tshirt_enfant', 'T-shirt Enfant'), ('sweat_enfant', 'Sweatshirt Enfant'), ('pantalon_enfant', 'Pantalon Enfant'), ('short_enfant', 'Short Enfant'), ('robe_enfant', 'Robe Enfant'), ('jupe_enfant', 'Jupe Enfant'), ('veste_enfant', 'Veste Enfant'), ('manteau_enfant', 'Manteau Enfant'), ('pyjama_enfant', 'Pyjama Enfant'), ('body_enfant', 'Body Enfant'), ('pull_enfant', 'Pull Enfant'), ('sousvetement_enfant', 'Sous-vêtements Enfant'), ('tshirt', 'T-shirt'), ('jeans', 'Jeans'), ('sweat', 'Sweatshirt'), ('pantalon_sport', 'Pantalon de sport'), ('baskets', 'Baskets'), ('doudoune', 'Doudoune'), ('pyjama', 'Pyjama'), ('casquette', 'Casquette'), ('bonnet', 'Bonnet'), ('echarpe', 'Écharpe'), ('gants', 'Gants')], default='jeans', max_length=100, verbose_name='Type de vêtement')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('enfant', 'Enfant')], db_index=True, default='homme', max_length=20, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (HTG)')),
                ('quantite_en_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL image externe')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image locale')),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('noir', 'Noir'), ('blanc', 'Blanc'), ('jaune', 'Jaune'), ('gris', 'Gris'), ('marron', 'Marron'), ('rose', 'Rose'), ('orange', 'Orange')], default='noir', max_length=20, verbose_name='Couleur')),
                ('populaire', models.BooleanField(db_index=True, default=False, verbose_name='Populaire')),
                ('nouveau', models.BooleanField(db_index=True, default=False, verbose_name='Nouveau')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
