# Generated by Django 4.2.16 on 2026-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='commentaires_photos/', verbose_name='Photo')),
                ('texte', models.TextField(verbose_name='Commentaire')),
                ('role', models.CharField(default='Client', max_length=100, verbose_name='Rôle')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date'],
            },
        ),
    ]
